// vue-app/src/components/customers-list/customers-list-display.vue
<template functional>
  <table class="table table-hover table-condensed">
    <thead>
    <tr>
      <th>#</th>
      <th>First Name</th>
      <th>Last Name</th>
      <th></th>
    </tr>
    </thead>
    <tbody>
      <customers-list-item v-for="customer in props.customers" :key="customer.id" :customer="customer" :deleteCustomer="props.deleteCustomer"/>
    </tbody>
  </table>
</template>

// react-app/src/components/customers/customers-list-display.jsx
import React from 'react';

import {CustomersListItem} from './customers-list-item.jsx';

export const CustomersListDisplay = props =>
<table className="table table-hover table-condensed">
  <thead>
    <tr>
      <th>#</th>
      <th>First Name</th>
      <th>Last Name</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
  {
    props.customers
      .map(customer => <CustomersListItem key={customer.id} customer={customer} deleteCustomer={props.deleteCustomer}/>)
  }
  </tbody>
</table>;
