// vue-app/src/components/customers-list/customers-list.vue
<template>
    <div class="panel panel-default panel-table">
    <div class="panel-heading">
      <div class="row">
        <div class="col col-xs-6">
          <h3 class="panel-title">Customers list</h3>
        </div>
        <div class="col col-xs-6 text-right">
          <button v-if="customers.list && customers.list.length > 0" @click="clearCustomers" type="button" class="btn btn-sm btn-danger">Clear</button>
          <button type="button" @click="createCustomer" class="btn btn-sm btn-success">Create</button>
        </div>
      </div>
    </div>
    <div class="panel-body">
      <div v-if="customers.list && customers.list.length <= 0">Pas de clients</div>
      <customers-list-display v-else :customers="customers.list" :deleteCustomer="deleteCustomer"/>
    </div>
  </div>
</template>
<script src="./customers-list.js"></script>

// react-app/src/components/customers/customers-list.jsx
import React from 'react';

import CustomersListDisplay from './customers-list-display.jsx';

const CustomersList = props => {
  const hasCustomers = props.customers.length >= 1;

  return (
    <div className="panel panel-default panel-table">
      <div className="panel-heading">
        <div className="row">
          <div className="col col-xs-6">
            <h3 className="panel-title">Customers list</h3>
          </div>
          <div className="col col-xs-6 text-right">
            {!hasCustomers ? null : (
              <button
                onClick={props.clearCustomers}
                type="button"
                className="btn btn-sm btn-danger">
                Clear
              </button>
            )}
            <button
              onClick={props.addItem}
              type="button"
              className="btn btn-sm btn-success">
              Create
            </button>
          </div>
        </div>
      </div>
      <div className="panel-body">
        {!hasCustomers ? (
          <div>Pas de clients</div>
        ) : (
          <CustomersListDisplay
            customers={props.customers}
            deleteCustomer={props.deleteCustomer}
          />
        )}
      </div>
    </div>
  );
};

export default CustomersList;
