// vue-app-2018/src/app.vue
<template functional> <!-- Flag this component to not have component definition (JS) -->
  <div>
    <nav class="navbar navbar-inverse navbar-static-top">
      <div class="container-fluid">
        <div class="navbar-header">
          <a class="navbar-brand" href="#">Vue-App</a>
        </div>

        <div class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
              <!-- Use router to navigate -->
              <router-link to="/" tag="li" exact-active-class="active"><a>Home</a></router-link>
              <router-link to="/customers" tag="li" exact-active-class="active"><a>Customers</a></router-link>
          </ul>
        </div>
      </div>
    </nav>

    <!-- Replace content with current page url-->
    <router-view></router-view>
  </div>
</template>

// react-app/src/app.jsx
import React from 'react';
import {Link, Route, Switch} from 'react-router-dom';

import {CustomersListContainer} from './containers/customers-list';
import {CustomerSheetContainer} from './containers/customer-sheet';
import {Dashboard} from './components/dashboard/dashboard.jsx';

export const App = () => {
  return (
    <div>
      <nav className="navbar navbar-inverse navbar-static-top">
        <div className="container-fluid">
          <div className="navbar-header">
            <a className="navbar-brand" href="#">React-App</a>
          </div>

          <div className="collapse navbar-collapse">
            <ul className="nav navbar-nav">
              <li className="active">
                <Link to='/'>Home</Link>
              </li>
              <li>
                <Link to='/customers'>Customers</Link>
              </li>
            </ul>
          </div>
        </div>
      </nav>

      <Switch>
        <Route exact path='/' component={Dashboard}/>
        <Route exact path='/customers' component={CustomersListContainer}/>
        <Route path='/customers/:id' component={CustomerSheetContainer}/>
      </Switch>
      { /*
        customers && (
          <Route path='/customers/:id' render={({match}) => (
            <CustomerSheet customer={this.stats.customers[0]}/>
          )}/>)
      */}
    </div>
  )
}
