// react-app/src/components/customers/customers-list-item.jsx
import React from 'react';
import {Link} from 'react-router-dom';

export const CustomersListItem = props =>
<tr>
  <th scope="row">{props.customer.id}</th>
  <td>{props.customer.firstname}</td>
  <td>{props.customer.lastname}</td>
  <td align="center">
    <Link to={`/customers/${props.customer.id}`} className="btn btn-default">
      <i className="fa fa-eye"></i>
    </Link>
    <Link to={`/customers/${props.customer.id}/edit`} className="btn btn-default">
      <i className="fa fa-pencil"></i>
    </Link>
    <a className="btn btn-default">
      <i className="fa fa-trash"></i>
    </a>
  </td>
</tr>;

// vue-app/src/components/customers-list/customers-list-item.vue
<template functional>
  <tr>
    <th scope="row">{{props.customer.id}}</th>
    <td>{{props.customer.firstname}}</td>
    <td>{{props.customer.lastname}}</td>
    <td align="center">
      <router-link :to="`/customer/${props.customer.id}`" class="btn btn-default">
        <i class="fa fa-eye"></i>
      </router-link>

      <router-link :to="`/customer/${props.customer.id}/edit`" exact class="btn btn-default">
        <i class="fa fa-pencil"></i>
      </router-link>

        <a class="btn btn-default" @click="props.deleteCustomer(props.customer.id)">
            <i class="fa fa-trash"></i>
        </a>
    </td>
  </tr>
</template>
